# Stack file is held only for integration with ghc-mod, nix build system is
# major one.
resolver: lts-9.4
packages:
- .
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 0ff348332fc05521172fb44cef67ece8926c3937
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: f3b310145a1afa6b448bdb060141ec16c18f0342
  extra-dep: true
  subdirs:
    - 'reflex-dom-core'
    - 'reflex-dom'

extra-deps:
  - dependent-sum-template-0.0.0.6
  - ghcjs-dom-0.9.2.0
  - ghcjs-dom-jsaddle-0.9.2.0
  - gi-javascriptcore-4.0.14
  - gi-webkit2-4.0.14
  - jsaddle-0.9.4.0
  - jsaddle-dom-0.9.2.0
  - jsaddle-webkit2gtk-0.9.0.0
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - webkit2gtk3-javascriptcore-0.14.2.1
  - zenc-0.1.1
